# Generated by Django 2.2.15 on 2020-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201120_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_name_url',
            field=models.CharField(default='helloworld', max_length=254),
            preserve_default=False,
        ),
    ]
