# Generated by Django 2.2.15 on 2021-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_article_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
