# Generated by Django 2.2.15 on 2021-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210601_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
