# Generated by Django 2.2.15 on 2021-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earwear', '0002_auto_20210606_2030'),
        ('articles', '0007_articles_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='which_earbud',
            field=models.ManyToManyField(blank=True, to='earwear.EarModelName'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='which_mobile',
            field=models.ManyToManyField(blank=True, to='mobiles.MobileVariant'),
        ),
    ]
