# Generated by Django 2.2.15 on 2021-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0001_initial'),
        ('articles', '0008_auto_20210606_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='Team gadgetin.in', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='which_wearable',
            field=models.ManyToManyField(blank=True, to='wearable.WearModelName'),
        ),
    ]
