# Generated by Django 2.2.15 on 2021-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_list_time', models.DateTimeField(blank=True, null=True)),
                ('article_list_time', models.DateTimeField(blank=True, null=True)),
                ('common_list_time', models.DateTimeField(blank=True, null=True)),
                ('earwear_list_time', models.DateTimeField(blank=True, null=True)),
                ('headphone_list_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
