# Generated by Django 2.2.15 on 2021-06-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarBrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_brand_name', models.CharField(max_length=50)),
                ('ear_brand_name_url', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='EarModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_name', models.CharField(max_length=50)),
                ('ear_price', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_name_url', models.SlugField()),
                ('ear_picture', models.ImageField(upload_to='ear_picture/')),
                ('ear_picture_credit', models.URLField()),
                ('ear_release_date', models.DateField(blank=True, null=True)),
                ('ear_availability', models.BooleanField(default=True)),
                ('ear_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Available', 'Available'), ('not available', 'not-available'), ('Rumored', 'Rumored')], default='Available', max_length=15)),
                ('ear_type', models.CharField(choices=[('Pure Wireless', 'pure-wireless'), ('In Ear Wireless', 'in-ear-wireless'), ('On Ear Wireless', 'on-ear-wireless'), ('In Ear Wired', 'in-ear-wired'), ('On Ear Wired', 'on-ear-wired')], max_length=20)),
                ('ear_mic', models.BooleanField(default=True)),
                ('ear_mic_features', models.CharField(blank=True, default='Active noise cancellation', max_length=500, null=True)),
                ('ear_battery', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_battery_feature', models.CharField(blank=True, default='Charging time:2, Play Time:15 hours, standby Time:100hours', max_length=1000, null=True)),
                ('ear_battery_connectivity', models.CharField(blank=True, default='Bluetooth v5.0, USB Type-C', max_length=500, null=True)),
                ('ear_waterproof', models.CharField(blank=True, default='Yes, IPX7', max_length=100, null=True)),
                ('ear_colors', models.CharField(blank=True, max_length=100, null=True)),
                ('ear_other_features', models.CharField(blank=True, default='Bluetooth Range:10m', max_length=1200, null=True)),
                ('inside_package', models.CharField(blank=True, max_length=500, null=True)),
                ('earBrandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earwear.EarBrandName')),
            ],
        ),
        migrations.CreateModel(
            name='EarOnlinePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_flipkart', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_flipkart_URL', models.URLField(blank=True, null=True)),
                ('ear_amazon', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_amazon_URL', models.URLField(blank=True, null=True)),
                ('ear_tata_cliq', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_tata_cliq_URL', models.URLField(blank=True, null=True)),
                ('ear_reliance_digital', models.PositiveIntegerField(blank=True, null=True)),
                ('ear_reliance_digital_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarVariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_image', models.ImageField(upload_to='ear_image/')),
                ('earImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ear_Image', to='earwear.EarModelName')),
            ],
        ),
        migrations.AddField(
            model_name='earmodelname',
            name='ear_price_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='earwear.EarOnlinePrice'),
        ),
    ]
