# Generated by Django 2.2.15 on 2021-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earwear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_mi_store',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_mi_store_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_oppo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_oppo_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_realme',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_realme_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_samsung',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_samsung_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_vivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earonlineprice',
            name='ear_vivo_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
