# Generated by Django 2.2.15 on 2020-09-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, unique=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand-logo/')),
            ],
        ),
        migrations.CreateModel(
            name='MobileBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity', models.IntegerField()),
                ('battery_type', models.CharField(blank=True, choices=[('LI-ION', 'Li-ion'), ('LI-POLY', 'Li-poly')], max_length=1, null=True)),
                ('fast_charger', models.BooleanField(blank=True, default=True, null=True)),
                ('fast_charging', models.CharField(blank=True, max_length=200, null=True)),
                ('replaceable', models.BooleanField(blank=True, default=False, null=True)),
                ('talk_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_camera', models.IntegerField()),
                ('primary_camera_str', models.CharField(max_length=501)),
                ('primary_camera_features', models.CharField(max_length=500)),
                ('secondary_camera', models.IntegerField()),
                ('secondary_camera_str', models.CharField(max_length=50)),
                ('secondary_camera_features', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MobileConnectivityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_type', models.CharField(choices=[('NANO', 'Nano'), ('MICRO', 'Micro'), ('STANDARD', 'Standard')], default='NANO', max_length=1)),
                ('five_g', models.BooleanField(default=False)),
                ('four_g', models.BooleanField(default=True)),
                ('three_g', models.BooleanField(default=True)),
                ('two_g', models.BooleanField(default=True)),
                ('SAR_value', models.CharField(blank=True, max_length=100, null=True)),
                ('wi_fi', models.CharField(blank=True, max_length=100, null=True)),
                ('bluetooth', models.CharField(blank=True, default='v5.0', max_length=100, null=True)),
                ('GPS', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.FloatField()),
                ('resolution', models.CharField(max_length=50)),
                ('resolution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('GPU', models.CharField(blank=True, max_length=50, null=True)),
                ('display_type', models.CharField(max_length=100)),
                ('display_features', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('os', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'ios')], max_length=1)),
                ('os_version', models.CharField(blank=True, max_length=10, null=True)),
                ('UI_version', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('slots', models.CharField(default='Dual SIM(2) + Dedicated Memory Card Slot', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MobileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=50)),
                ('mobile_image', models.ImageField(upload_to='mobile_image/')),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles_name', to='mobiles.BrandName')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.PositiveIntegerField()),
                ('processor', models.CharField(max_length=50)),
                ('processor_company', models.CharField(max_length=50)),
                ('clock_speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_sensor', models.BooleanField(default=True)),
                ('fingerprint_position', models.CharField(blank=True, choices=[('SIDE', 'Side'), ('REAR', 'REAR'), ('FRONTSIDE', 'Front Side'), ('ONSCREEN', 'Onscreen')], max_length=1, null=True)),
                ('other_sensor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MobileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_storage', models.PositiveIntegerField()),
                ('expandable_memory', models.BooleanField(default=True)),
                ('expandable_memory_capacity', models.IntegerField(blank=True, null=True)),
                ('OTG_support', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipkart', models.PositiveIntegerField(blank=True, null=True)),
                ('amazon', models.PositiveIntegerField(blank=True, null=True)),
                ('tata_cliq', models.PositiveIntegerField(blank=True, null=True)),
                ('reliance_digital', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_Feature', models.CharField(blank=True, max_length=500, null=True)),
                ('in_the_box', models.CharField(blank=True, max_length=300, null=True)),
                ('warranty', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipkart_URL', models.URLField(blank=True, null=True)),
                ('amazon_URL', models.URLField(blank=True, null=True)),
                ('tata_cliq_URL', models.URLField(blank=True, null=True)),
                ('reliance_digital_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_image', models.ImageField(upload_to='variant_image/')),
            ],
        ),
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_color', models.CharField(max_length=50)),
                ('price_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.OnlinePrice')),
            ],
        ),
        migrations.CreateModel(
            name='MobileVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_variants', models.CharField(max_length=20)),
                ('image_credit', models.URLField()),
                ('mobileBattery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileBattery')),
                ('mobileCamera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileCamera')),
                ('mobileDisplay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileDisplay')),
                ('mobileGeneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileGeneral')),
                ('mobileNames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobileName', to='mobiles.MobileName')),
                ('mobilePerformance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobilePerformance')),
                ('mobileSensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileSensor')),
                ('mobileStorage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileStorage')),
                ('otherFeature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.OtherFeature')),
                ('variantColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.VariantColor')),
                ('variantImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.VariantImage')),
            ],
        ),
        migrations.CreateModel(
            name='MobileConnectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_name', models.CharField(choices=[('SIM 1', 'SIM 1'), ('SIM 2', 'SIM 2'), ('SIM 3', 'SIM 3')], max_length=1)),
                ('audio_jack', models.CharField(default='3.5 mm', max_length=30)),
                ('USB_type_c', models.BooleanField(blank=True, default=True, null=True)),
                ('mobileConnectivity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileConnectivityDetails')),
                ('mobileVariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileVariant')),
            ],
        ),
    ]
