# Generated by Django 2.2.14 on 2020-07-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MobileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=30)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandName', to='mobiles.BrandName')),
            ],
        ),
        migrations.CreateModel(
            name='MobileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_spec', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('launch_date', models.DateTimeField()),
                ('ram', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('mobileNames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobileName', to='mobiles.MobileName')),
            ],
        ),
    ]
