# Generated by Django 2.2.15 on 2020-09-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineprice',
            name='priceURL',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.PriceURL'),
        ),
    ]
