# Generated by Django 2.2.15 on 2020-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilename',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_image/'),
        ),
    ]
