# Generated by Django 2.2.15 on 2020-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_auto_20200916_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilename',
            name='mobile_image',
            field=models.ImageField(upload_to='mobile_image/'),
        ),
    ]
