# Generated by Django 2.2.15 on 2020-08-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_auto_20200816_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandname',
            name='image_credits',
        ),
    ]
