# Generated by Django 2.2.15 on 2020-09-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20200916_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileconnectivity',
            name='mobileConnectivityDetails',
        ),
        migrations.AddField(
            model_name='mobileconnectivitydetails',
            name='mobileConnectivityDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileConnectivity'),
        ),
        migrations.AlterField(
            model_name='mobileconnectivitydetails',
            name='sim_name',
            field=models.CharField(choices=[('SIM 14g', 'SIM 1'), ('SIM 24g', 'SIM 2'), ('SIM 3', 'SIM 3')], max_length=10),
        ),
    ]
