# Generated by Django 2.2.15 on 2020-09-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_remove_brandname_image_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_storage', models.IntegerField()),
                ('expandable_memory', models.BooleanField(default=True)),
                ('expandable_memory_capacity', models.IntegerField()),
                ('OTG_support', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_variants', models.CharField(max_length=20)),
                ('mobileNames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobileName', to='mobiles.MobileName')),
                ('mobileStorage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobiles.MobileStorage')),
            ],
        ),
        migrations.DeleteModel(
            name='MobileDetails',
        ),
    ]
