# Generated by Django 2.2.15 on 2020-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20200916_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileconnectivitydetails',
            name='VoLTE',
            field=models.BooleanField(default=True),
        ),
    ]
