# Generated by Django 2.2.15 on 2020-09-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_mobileconnectivitydetails_volte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilename',
            name='phone_type',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet')], default='Smartphone', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileconnectivitydetails',
            name='mobileConnectivityDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_connectivity_details', to='mobiles.MobileConnectivity'),
        ),
        migrations.AlterField(
            model_name='mobileconnectivitydetails',
            name='sim_name',
            field=models.CharField(choices=[('SIM 1', 'SIM 1'), ('SIM 2', 'SIM 2'), ('SIM 3', 'SIM 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mobilevariant',
            name='mobileNames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_Variant', to='mobiles.MobileName'),
        ),
    ]
