# Generated by Django 2.2.15 on 2020-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0010_auto_20200924_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledisplay',
            name='display_features',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='mobileperformance',
            name='processor_company',
            field=models.CharField(choices=[('Qualcomm', 'Qualcomm'), ('MediaTek', 'MediaTek')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mobilesensor',
            name='fingerprint_position',
            field=models.CharField(blank=True, choices=[('SIDE', 'Side'), ('REAR', 'REAR'), ('FRONTSIDE', 'Front Side'), ('IN-DISPLAY', 'in-display')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeature',
            name='other_Feature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
