# Generated by Django 2.2.15 on 2020-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0012_auto_20201120_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilename',
            name='mobile_name_url',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileperformance',
            name='processor_company',
            field=models.CharField(choices=[('Qualcomm', 'Qualcomm'), ('MediaTek', 'MediaTek'), ('Apple', 'Apple'), ('HiSilicon', 'HiSilicon'), ('Samsung', 'Samsung')], max_length=50),
        ),
    ]
