# Generated by Django 2.2.15 on 2020-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0013_auto_20201206_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilevariant',
            name='mobile_variants_url',
            field=models.CharField(default='1-gb-ram,-16-gb-storage', max_length=50),
        ),
    ]
