# Generated by Django 2.2.15 on 2020-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0014_mobilevariant_mobile_variants_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandname',
            name='brand_name_url',
            field=models.CharField(default='comepn', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobileperformance',
            name='clock_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilevariant',
            name='mobile_variants_url',
            field=models.CharField(default='1-gb-ram-16-gb-storage', max_length=50),
        ),
    ]
