# Generated by Django 2.2.15 on 2021-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0017_auto_20210112_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebattery',
            name='talk_time',
        ),
        migrations.AddField(
            model_name='mobilegeneral',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Available', 'Available'), ('not available', 'not available'), ('Rumored', 'Rumored')], default='Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobilecamera',
            name='primary_camera_features',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='mobilecamera',
            name='secondary_camera_features',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
