# Generated by Django 2.2.15 on 2021-03-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0018_auto_20210310_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineprice',
            name='mi_store',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='mi_store_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='oppo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='oppo_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='realme',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='realme_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='samsung',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='samsung_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='vivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineprice',
            name='vivo_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
