# Generated by Django 2.2.15 on 2021-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0019_auto_20210322_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegeneral',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Available', 'Available'), ('not available', 'not available'), ('Rumored', 'Rumored')], default='Available', max_length=15),
        ),
    ]
