# Generated by Django 2.2.15 on 2021-07-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WearBrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_brand_name', models.CharField(max_length=50)),
                ('wear_brand_name_url', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='WearConnectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_callfunction', models.CharField(blank=True, default='No,', max_length=500, null=True)),
                ('wear_bluetooth', models.CharField(blank=True, default='Yes, Version:5.1', max_length=50, null=True)),
                ('wear_wifi', models.CharField(blank=True, default='No,', max_length=50, null=True)),
                ('wear_GPS', models.CharField(blank=True, default='Yes,', max_length=50, null=True)),
                ('other_con_features', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_dimensions', models.CharField(blank=True, default='77 mm x 77 mm x  77 mm', max_length=50, null=True)),
                ('wear_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_resolutions', models.CharField(blank=True, default='320 x 320 Pixels', max_length=50, null=True)),
                ('wear_size', models.FloatField(blank=True, null=True)),
                ('wear_type', models.CharField(blank=True, default='LCD', max_length=50, null=True)),
                ('wear_display_features', models.CharField(blank=True, default='HD Display', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_name', models.CharField(max_length=50)),
                ('wear_name_url', models.SlugField()),
                ('wear_price', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_picture', models.ImageField(upload_to='wear_picture/')),
                ('wear_picture_credit', models.URLField()),
                ('wear_release_date', models.DateField(blank=True, null=True)),
                ('wear_availability', models.BooleanField(default=True)),
                ('wear_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Available', 'Available'), ('not available', 'not-available'), ('Rumored', 'Rumored')], default='Available', max_length=15)),
                ('wear_type', models.CharField(choices=[('Band', 'band'), ('Watch', 'watch')], max_length=20)),
                ('ideal_for', models.CharField(blank=True, default='Unisex', max_length=200, null=True)),
                ('wear_touch', models.BooleanField(default=True)),
                ('wear_os', models.CharField(blank=True, max_length=100, null=True)),
                ('wear_functions', models.CharField(blank=True, max_length=800, null=True)),
                ('wear_compatible_device', models.CharField(blank=True, default='Phones with Android 5.0 and Above or IOS 10 and Above', max_length=200, null=True)),
                ('wear_sensors', models.CharField(blank=True, max_length=200, null=True)),
                ('wear_battery', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_battery_feature', models.CharField(blank=True, default='Charging time:120 minutes, Battery Life:10 days, Battery Type: Lithiun Polymer', max_length=1000, null=True)),
                ('wear_material', models.CharField(blank=True, max_length=100, null=True)),
                ('wear_water_resistant', models.CharField(blank=True, default='Yes, upto 50 m', max_length=100, null=True)),
                ('wear_colors', models.CharField(blank=True, default='Dial Color:Black & Strap Color:Blue', max_length=100, null=True)),
                ('wear_other_features', models.CharField(blank=True, max_length=1200, null=True)),
                ('inside_package', models.CharField(blank=True, max_length=500, null=True)),
                ('wearBrandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wearable.WearBrandName')),
                ('wearConnectivity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearable.WearConnectivity')),
                ('wearDimensions', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearable.WearDimensions')),
                ('wearDisplay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearable.WearDisplay')),
            ],
        ),
        migrations.CreateModel(
            name='WearOnlinePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_flipkart', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_flipkart_URL', models.URLField(blank=True, null=True)),
                ('wear_amazon', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_amazon_URL', models.URLField(blank=True, null=True)),
                ('wear_tata_cliq', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_tata_cliq_URL', models.URLField(blank=True, null=True)),
                ('wear_reliance_digital', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_reliance_digital_URL', models.URLField(blank=True, null=True)),
                ('wear_mi_store', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_mi_store_URL', models.URLField(blank=True, null=True)),
                ('wear_samsung', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_samsung_URL', models.URLField(blank=True, null=True)),
                ('wear_vivo', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_vivo_URL', models.URLField(blank=True, null=True)),
                ('wear_realme', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_realme_URL', models.URLField(blank=True, null=True)),
                ('wear_oppo', models.PositiveIntegerField(blank=True, null=True)),
                ('wear_oppo_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearVariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_image', models.ImageField(upload_to='wear_image/')),
                ('wearImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wear_Image', to='wearable.WearModelName')),
            ],
        ),
        migrations.AddField(
            model_name='wearmodelname',
            name='wear_price_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearable.WearOnlinePrice'),
        ),
    ]
