# Generated by Django 2.2.15 on 2021-07-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wearable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearmodelname',
            name='wear_price_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearable.WearOnlinePrice'),
        ),
    ]
