brand_name_values = [{"name": "apple",
                      "description": "Looking for Apple phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Apple phones",
                      "heading": "List of Apple Phones"},
                     {"name": "google",
                      "description": "Looking for Google phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Google phones",
                      "heading": "List of Google Phones"},
                     {"name": "honor",
                      "description": "Looking for Honor phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Honor phones",
                      "heading": "List of Honor Phones"},
                     {"name": "huawei",
                      "description": "Looking for Huawei phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Huawei phones",
                      "heading": "List of Huawei Phones"},
                     {"name": "infinix",
                      "description": "Looking for Infinix phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Infinix phones",
                      "heading": "List of Infinix Phones"},
                     {"name": "iqoo",
                      "description": "Looking for IQOO phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of IQOO phones",
                      "heading": "List of IQOO Phones"},
                     {"name": "lg",
                      "description": "Looking for LG phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of LG phones",
                      "heading": "List of LG Phones"},
                     {"name": "micromax",
                      "description": "Looking for Micromax phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Micromax phones",
                      "heading": "List of Micromax Phones"},
                     {"name": "motorola",
                      "description": "Looking for Motorola phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Motorola phones",
                      "heading": "List of Motorola Phones"},
                     {"name": "nokia",
                      "description": "Looking for Nokia phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Nokia phones",
                      "heading": "List of Nokia Phones"},
                     {"name": "oneplus",
                      "description": "Looking for Oneplus phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Oneplus phones",
                      "heading": "List of Oneplus Phones"},
                     {"name": "oppo",
                      "description": "Looking for oppo phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of oppo phones",
                      "heading": "List of OPPO Phones"},
                     {"name": "poco",
                      "description": "Looking for poco phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of poco phones",
                      "heading": "List of POCO Phones"},
                     {"name": "realme",
                      "description": "Looking for Realme phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Realme phones",
                      "heading": "List of Realme Phones"},
                     {"name": "samsung",
                      "description": "Looking for Samsung phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Samsung phones",
                      "heading": "List of Samsung Phones"},
                     {"name": "vivo",
                      "description": "Looking for Vivo phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Vivo phones",
                      "heading": "List of Vivo Phones"},
                     {"name": "xiaomi",
                      "description": "Looking for Xiaomi phone!!! Visit now to Get the full details, price, reviews, videos and manymore....",
                      "title": "Get the full list of Xiaomi phones",
                      "heading": "List of Xiaomi Phones"}, ]


other_list_items = [{"name": "latest-phones",
                     "filter_set": {'mobileGeneral__status': 'Available', 'mobileGeneral__is_available': True, 'mobileNames__phone_type': 'SMARTPHONE'},
                     "description": "Looking for latest phones?? Visit now to Get the full details, price, reviews, videos and manymore....",
                     "title": "The entire list of latest smartphones",
                     "heading": "Latest Phones"},
                    {"name": "budget-phones",
                     "filter_set": {'mobileGeneral__price__gte': 9000, 'mobileGeneral__price__lte': 11500, 'mobileGeneral__status': 'Available', 'mobileGeneral__is_available': True, 'mobileNames__phone_type': 'SMARTPHONE'},
                     "description": "Looking for a phone that suits to your pocket...!! Visit now to Get the full details, price, reviews, videos and manymore....",
                     "title": "find out budget range smartphones",
                     "heading": "Budget Phones"},
                    {"name": "smartphones",
                     "filter_set": {'mobileGeneral__status': 'Available', 'mobileGeneral__is_available': True, 'mobileNames__phone_type': 'SMARTPHONE'},
                     "description": "Get the list of all mobile phone listed in India. Visit now to Get the full details, price, reviews, videos and manymore....",
                     "title": "See comprehensive list of mobile phones in India",
                     "heading": "List of Smartphones"},
                    {"name": "tablets",
                     "filter_set": {'mobileGeneral__status': 'Available', 'mobileGeneral__is_available': True, 'mobileNames__phone_type': 'TABLET'},
                     "description": "Get the list of all tablets listed in India. Visit now to Get the full details, price, reviews, videos and manymore....",
                     "title": "Checkout whole list of tablets released in India",
                     "heading": "List of Tablets"}
                    ]
